---
- name: Restart ssh
  service:
    name: ssh
    state: restarted

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Reload sysctl
  command: sysctl --system
  changed_when: false
