---
- name: Update and upgrade apt packages
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Remove useless packages from the cache
  apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: true
