---
- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker

- name: Install Docker Engine and plugins
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Remove AppArmor in LXC containers to fix permissions
  apt:
    name:
      - apparmor
      - apparmor-utils
    state: absent
  when: ansible_facts['virtualization_type'] == 'lxc'
  notify: Restart Docker

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

- name: Add user to docker group (Allow docker without sudo)
  user:
    name: "{{ target_user }}"
    groups: docker
    append: true
  when: docker_add_user_to_group | bool
